name: "sac"
learning_steps: 1000000
buffer_capacity: 1000000
activation: "relu"
discount: 0.99
batch_size: 256
eval_rollouts: 10
eval_frequency: 5000
seed: 42
seed_steps: 25000

# critic
critic_hidden_dimension: 256
critic_hidden_layers: 2
critic_learning_rate: 0.0003
critic_betas: [0.9, 0.999]
critic_target_update_frequency: 2
critic_tau: 0.005

# actor
actor_hidden_dimension: 256
actor_hidden_layers: 2
actor_learning_rate: 0.0003
actor_betas: [0.9, 0.999]
actor_log_std_bounds: [-20, 2]
actor_update_frequency: 1

# alpha
alpha_learning_rate: 0.0003
alpha_betas: [0.9, 0.999]
init_temperature: 0.5
learnable_temperature: False


