name: "gciql"
learning_steps: 1000000
buffer_capacity: 1000000
activation: "relu"
discount: 0.99
batch_size: 1024
eval_rollouts: 10
eval_frequency: 20000
z_inference_steps: 10000
seed: 42

temperature: 1
expectile: 0.7

# critic
critic_hidden_dimension: 1024
critic_hidden_layers: 2
value_learning_rate: 0.0001
critic_target_update_frequency: 1
critic_tau: 0.005

# actor
actor_hidden_dimension: 1024
actor_hidden_layers: 2
actor_learning_rate: 0.0001
actor_update_frequency: 1
